### Create a new contracor review
POST http://localhost:3334/api/review HTTP/1.1
Content-Type: application/json

{
  "rating": 5,
  "taskId": 1,
  "text": "The material world is full of light. Paradise is not the pure joy of the sinner."
}

### Get a review by ID
GET http://localhost:3334/api/review/1 HTTP/1.1

### Get reviews
GET http://localhost:3334/api/review HTTP/1.1

