### Create a new contracor review
POST http://localhost:3334/api/review HTTP/1.1
Content-Type: application/json

{
  "rating": 5,
  "taskId": 3,
  "contractorId": "31e42365-5502-4238-9233-5b2fe994909f",
  "text": "Some contractor review"
}

### Get a review by ID
GET http://localhost:3334/api/review/1 HTTP/1.1

### Get a reviews
GET http://localhost:3334/api/review HTTP/1.1

