### Upload a task file
POST http://localhost:3332/api/upload/task/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MyNjg0Mzc1OTE0MzI3ZjY0YWE4ZjAiLCJlbWFpbCI6InNhbGxpZS5jbGV2ZWxhbmQzQGV4YW1wbGUuY29tIiwibmFtZSI6IkthdGhlcmluYSBQZmFubmVyc3RpbGwiLCJpYXQiOjE2NzM4MTI2MTIsImV4cCI6MTY3MzgxMzUxMn0.uV8_Eh9-3q7D3vMTxkt0mGuzAg0CtRq0_pTB2EZCdx4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="hill.jpg"
Content-Type: image/jpeg

< /Users/sk/Desktop/tmp/hill.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Upload an avatar file
POST http://localhost:3332/api/upload/avatar/63c2684375914327f64aa8f0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MyNjg0Mzc1OTE0MzI3ZjY0YWE4ZjAiLCJlbWFpbCI6InNhbGxpZS5jbGV2ZWxhbmQzQGV4YW1wbGUuY29tIiwibmFtZSI6IkthdGhlcmluYSBQZmFubmVyc3RpbGwiLCJpYXQiOjE2NzM4MTI2MTIsImV4cCI6MTY3MzgxMzUxMn0.uV8_Eh9-3q7D3vMTxkt0mGuzAg0CtRq0_pTB2EZCdx4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/jpeg

< /Users/sk/Desktop/tmp/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get a file
GET http://localhost:3332/api/upload/1673717685125.hill.jpg
