### Create a new task
POST http://localhost:3334/api/task/ HTTP/1.1
Content-Type: application/json

{
  "address": "Suite 538 47401 Gustavo Streets, New Ross, WV 00188",
  "budget": 100,
  "clientId": "63c2684375914327f64aa8f0",
  "description": "Last night, Darth Vader came down from Planet Vulcan and told me that if I didn't take Lorraine out, that he'd melt my brain.",
  "dueDate": "2024-11-30",
  "skills": [],
  "tags": [],
  "title": "So what if the most meaningful day."
}

### Update a task with ID
PATCH http://localhost:3334/api/task/5 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "DIVIO",
    "STELLA"
  ]
}

### Get a task by Id
GET http://localhost:3334/api/task/5 HTTP/1.1

### Get all task
GET http://localhost:3334/api/task HTTP/1.1

### Get filtered task
GET http://localhost:3334/api/task?sort=replies HTTP/1.1

### Delete a task
DELETE http://localhost:3334/api/task/1 HTTP/1.1
