### Create a new task
POST http://localhost:3334/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzk0MzM4MywiZXhwIjoxNjczOTQ0MjgzfQ.cQ39MJUtBVKUHJPrzzbWz-dkJxqviy_D0Ey2RV3lVrE

{
  "address": "Suite 538 47401 Gustavo Streets, New Ross, WV 00188",
  "budget": 100,
  "description": "Last night, Darth Vader came down from Planet Vulcan and told me that if I didn't take Lorraine out, that he'd melt my brain.",
  "dueDate": "2024-11-30",
  "skills": [],
  "tags": [],
  "title": "So what if the most meaningful day.",
  "city": "Владивосток"
}


### Update a task
PATCH http://localhost:3334/api/task/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzg3NzE2MCwiZXhwIjoxNjczODc4MDYwfQ.w9Gvu4r5viBuqE7lhPTiPr67BjHK1d2sKjqaAytiGzA

{
  "tags": [
    "DIVIO",
    "ANTVERPIA",
    "STELLA"
  ],
  "skills": [
    2
  ]
}


### Get a task by Id
GET http://localhost:3334/api/task/8 HTTP/1.1

### Get all task
GET http://localhost:3334/api/task?city=Москва HTTP/1.1

### Get new task
GET http://localhost:3334/api/task/new?skills=2&sort=replies&limit=2&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MzMDNhZjdhMzM4NWJkNzEzNDJlZDYiLCJlbWFpbCI6ImVkbW9uZC5tZXllckBleGFtcGxlLmNvbSIsIm5hbWUiOiJCcnlhbiBEYXJlIiwicm9sZSI6IkNvbnRyYWN0b3IiLCJpYXQiOjE2NzM4NzE4NDMsImV4cCI6MTY3Mzg3Mjc0M30.hh-5ZLWWgWksutFE5omoZCxdnUww8EeSe2lGmZ_leag

### Get my tasks
GET http://localhost:3334/api/task/my?status=New HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MzMDNhZjdhMzM4NWJkNzEzNDJlZDYiLCJlbWFpbCI6ImVkbW9uZC5tZXllckBleGFtcGxlLmNvbSIsIm5hbWUiOiJCcnlhbiBEYXJlIiwicm9sZSI6IkNvbnRyYWN0b3IiLCJpYXQiOjE2NzM4ODkxMzAsImV4cCI6MTY3Mzg5MDAzMH0.0F7HuqG6FMGI89Zq1sOodyAjSeAg8_J4e5aJFa2FClE


### Delete a task
DELETE http://localhost:3334/api/task/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzg1NTczMiwiZXhwIjoxNjczODU2NjMyfQ.zaxgpTLWz6-xpR6Nw9xyDQJl9KogioRUvYmlgiAOeTE


### Start a task
PATCH http://localhost:3334/api/task/9/accept?contractorId=63c303af7a3385bd71342ed6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzk0MzM4MywiZXhwIjoxNjczOTQ0MjgzfQ.cQ39MJUtBVKUHJPrzzbWz-dkJxqviy_D0Ey2RV3lVrE

### Finish a task
PATCH http://localhost:3334/api/task/8/done HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzk4NTM5NCwiZXhwIjoxNjczOTg2Mjk0fQ.2KPy35MZrMUUjL72qjpX5BAphZvOikl4suyx9lbQmHQ

{
  "rating": 4,
  "text": "The material world is full of light. Paradise is not the pure joy of the sinner."
}

### Fail a task
PATCH http://localhost:3334/api/task/8/fail HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3MzkxNTc1MywiZXhwIjoxNjczOTE2NjUzfQ.HsjLP9kuh_5bj4ixVP6528ljGROXFkAElO3hbkfrSmw


### Cancel a task
PATCH http://localhost:3334/api/task/9/cancel HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ZmU4NjYzNjlhZmVhODQ5YzhlYjgiLCJlbWFpbCI6ImtlcnJpLmR1ZGxleUBleGFtcGxlLmNvbSIsIm5hbWUiOiJHZXJhbGRpbmUgUm9tYWd1ZXJhIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3Mzk0MzM4MywiZXhwIjoxNjczOTQ0MjgzfQ.cQ39MJUtBVKUHJPrzzbWz-dkJxqviy_D0Ey2RV3lVrE
