### Create a new task
POST http://localhost:3334/api/task/ HTTP/1.1
Content-Type: application/json

{
  "address": "Some address",
  "budget": 100,
  "clientId": "638dac5ca3a0dafd519c1827",
  "description": "Last night, Darth Vader came down from Planet Vulcan and told me that if I didn't take Lorraine out, that he'd melt my brain.",
  "dueDate": "2024-11-30",
  "image": "image.jpg",
  "skills": [],
  "tags": [],
  "title": "Last night, Darth Vader came down"
}

### Update a task with ID
PATCH http://localhost:3334/api/task/1 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "DIVIO",
    "STELLA"
  ]
}

### Get a task by Id
GET http://localhost:3334/api/task/1 HTTP/1.1

### Get all task
GET http://localhost:3334/api/task HTTP/1.1

### Get filtered task
GET http://localhost:3334/api/task?sort=replies HTTP/1.1

### Delete a task
DELETE http://localhost:3334/api/task/1 HTTP/1.1
