### Create a new reply to a task
POST http://localhost:3334/api/reply HTTP/1.1
Content-Type: application/json

{
  "budget": 100,
  "comment": "The visitor hurts",
  "taskId": 122,
  "userId": "638dac5ca3a0dafd519c1829"
}

### Get a reply by ID
GET http://localhost:3334/api/reply/1 HTTP/1.1

### Get all replies
GET http://localhost:3334/api/reply HTTP/1.1

### Delete a reply by ID
DELETE http://localhost:3334/api/reply/3 HTTP/1.1
