### Create a new user
POST http://localhost:3335/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Ray Johnston",
  "email": "reva.valencia@example.com",
  "password": "123456",
  "city": "Москва",
  "birthDate": "2000-05-05",
  "role": "Contractor"
}

### Get a user by Id
GET http://localhost:3335/api/auth/63b14f0d7fbac2d53ecee035 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2ODNhYzA3ODUwNTEwZTU2MjNkNWMiLCJlbWFpbCI6Imp1bGVzLmNhbGR3ZWxsQGV4YW1wbGUuY29tIiwibmFtZSI6Ikp1ZGUgQ2Fzc2luIiwiaWF0IjoxNjcyOTE2NTE5LCJleHAiOjE2NzI5MTc0MTl9.zJ4FA2rAxOUkoQMotDBIHum_B9pwPhqsCKMn7zovwFc

### Login a user with email and password
POST http://localhost:3335/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "stacy.fischer@example.com",
  "password": "123456"
}

### Change the user password
PATCH http://localhost:3335/api/auth/register HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2ODNhYzA3ODUwNTEwZTU2MjNkNWMiLCJlbWFpbCI6Imp1bGVzLmNhbGR3ZWxsQGV4YW1wbGUuY29tIiwibmFtZSI6Ikp1ZGUgQ2Fzc2luIiwiaWF0IjoxNjcyOTE2NTE5LCJleHAiOjE2NzI5MTc0MTl9.zJ4FA2rAxOUkoQMotDBIHum_B9pwPhqsCKMn7zovwFc
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "654321"
}

### Update a user profile
PATCH http://localhost:3335/api/auth/profile/63a171ab88a698517390456b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2ODNhYzA3ODUwNTEwZTU2MjNkNWMiLCJlbWFpbCI6Imp1bGVzLmNhbGR3ZWxsQGV4YW1wbGUuY29tIiwibmFtZSI6Ikp1ZGUgQ2Fzc2luIiwiaWF0IjoxNjcyOTE2NTE5LCJleHAiOjE2NzI5MTc0MTl9.zJ4FA2rAxOUkoQMotDBIHum_B9pwPhqsCKMn7zovwFc
Content-Type: application/json

{
  "email": "finis@cirpi.ru",
  "name": "Silva",
  "phone": "999-100-6666",
  "skills": [
    "1",
    "2",
    "3"
  ]
}

### Logout
GET http://localhost:3335/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2ODNhYzA3ODUwNTEwZTU2MjNkNWMiLCJlbWFpbCI6Imp1bGVzLmNhbGR3ZWxsQGV4YW1wbGUuY29tIiwibmFtZSI6Ikp1ZGUgQ2Fzc2luIiwiaWF0IjoxNjcyOTE2MTgwLCJleHAiOjE2NzI5MTcwODB9.LlutPgiYp0MpS0qCqi4yYyw-q7rqAsIp_hLP22OwXug

### Refresh tokens
GET http://localhost:3335/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2ODNhYzA3ODUwNTEwZTU2MjNkNWMiLCJlbWFpbCI6Imp1bGVzLmNhbGR3ZWxsQGV4YW1wbGUuY29tIiwibmFtZSI6Ikp1ZGUgQ2Fzc2luIiwiaWF0IjoxNjcyOTE5NDE3LCJleHAiOjE2NzM1MjQyMTd9.0SUj2VcSJ5dCH3WLe2lyL-Igh8zWuYDsO2WHbeMN4UA
